# docker-compose for development and local testing
services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: test-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - bridge_net

  bridge:
    image: wcsi/modbus-mqtt-bridge
    container_name: modbus-bridge
    build:
      context: .
    depends_on:
      - mosquitto
    ports:
      - "1502:502"
    environment:
      - MQTT_HOSTNAME=mosquitto
      - MQTT_PORT=1883
      - CONFIG_FILE=/app/config/registers.json
    volumes:
      - ./config/registers.json:/app/config/registers.json
    networks:
      - bridge_net

networks:
  bridge_net:
    driver: bridge
