# docker-compose for development and local testing
services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: test-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - test_net

networks:
  test_net:
    driver: bridge
